### ISSUE TITLE
请问mjst和chs分别是什么含义呢？

### ISSUE THREAD

**Issue by 1193700079** [lancercat/VSDF#1]
![image](https://user-images.githubusercontent.com/43908729/177065096-5bebe030-96be-4c3e-983e-b08b607b7188.png)

看见代码里面出现了很多mjst和chs

**Comment by lancercat** [comment]
Question: I saw a lot mjst and chs in the code, what do they mean?

They are model names. 

mjst means model used for clost-set benchmarks, and chs indicates open-set models.

The names come from the data used in training.

**Comment by 1193700079** [comment]
ok , thank you!
