### ISSUE TITLE
The usage of the font parameter in the makept function.

### ISSUE THREAD

**Issue by 1193700079** [lancercat/VSDF#2]
When making pt format, I need to specify the font file, what is the purpose of this?
![image](https://user-images.githubusercontent.com/43908729/177260884-8438eab5-64e7-4d91-bc44-8e85d8ed447d.png)

**Comment by lancercat** [comment]
The framework uses glyphs from the font as side-information.

**Comment by lancercat** [comment]
Generally, give it a noto-san-serif font of the language in question should do.

**Comment by 1193700079** [comment]
> 

If I want to train in multiple languages, how do I do it？

**Comment by lancercat** [comment]
Merge multiple fonts, or hack it thru.

**Comment by lancercat** [comment]
by rewritting your own makept function

**Comment by 1193700079** [comment]
ok thank you！let me try

**Comment by lancercat** [comment]
BTW, mind me editing the title a bit?
From "Why is this character file in PT format?" to "The usage of the font parameter in the makept function"

**Comment by 1193700079** [comment]
> BTW, mind me editing the title a bit? From "Why is this character file in PT format?" to "The usage of the font parameter in the makept function"

ok ，Thanks for the trouble
