### ISSUE TITLE
How to specify multi - gpu training?

### ISSUE THREAD

**Issue by 1193700079** [lancercat/VSDF#3]
The default setting is to start only one gpu

**Comment by 1193700079** [comment]
by the way,
![image](https://user-images.githubusercontent.com/43908729/177483448-702bff86-0929-435e-947d-e931fbd4a178.png)

these variables:
choutput and ctxout
tarswunk and gtarswunk

What does that mean？

**Comment by lancercat** [comment]
1. Yup, it's designed to use only one GPU. MultiGPU will NOT be implemented in this work. 


2. variables

   choutput: prediction from the vision module
   
   ctxout: prediction from the semantic module
   
   tarswunk: local labels(TARgetS) in batch With UNKnown labels replaced(as the label sampler samples label)
 
   gtarswunk: Global labels(TARgetS) With UNKnown labels replaced for semantic module.

**Comment by 1193700079** [comment]
ok thank you !
