### ISSUE TITLE
How to run inference on single image?

### ISSUE THREAD

**Issue by XTMeow** [lancercat/VSDF#7]
Thank you for your hard work!
My problem is I dont know how to run inference on single image. I would be very appreciate if you can show me how to do it.

**Comment by lancercat** [comment]
Please refer to section IV of the manul.pdf.

**Comment by XTMeow** [comment]
I ran the code but it seems my gpu (2060) doesnt have enough vram. 
Thank you for your reply.

**Comment by lancercat** [comment]
Shan't be... Single image tests should only take 1.8Gib of vram or a little bit more than that...
![image](https://user-images.githubusercontent.com/59994105/218647229-87fe718c-37b4-49f5-988c-adaa5464ed07.png)

**Comment by XTMeow** [comment]
I wonder why that error appeared on my machine.
But I added "with torch.no_grad()" into the "pretest" function in file "neko_abstract_jtr.py" and my error disappeared.
![Screenshot from 2023-02-14 13-43-13](https://user-images.githubusercontent.com/125275473/218660587-6e1e524f-c3a6-476e-b752-eb5c9842dee0.png)
My result:
![Screenshot from 2023-02-14 13-55-39](https://user-images.githubusercontent.com/125275473/218662452-ed4bbe7a-d448-4ae5-bcf7-1a426e2510ca.jpg)
I dont know if my modification affected anything.

**Comment by lancercat** [comment]
Maybe you have a huge character set? (Just realized that you are handling CJK)
Adding  "with torch.no_grad()" is sure a valid fix to the vram issue, and it should bring no adversary affects.

I will merge this fix now, and huge thx for the feedback.
