### ISSUE TITLE
The gemometric attention in section 3.3 of the paper

### ISSUE THREAD

**Issue by bad-meets-joke** [lancercat/VSDF#8]
Hello, 

Sorry to bother you. I have two minor questions about the paper OpenCCD.

- What is the specific opreations of the geometric attention in Section 3.3?
- For zero-shot character recognition in Section 4.3, what is the size of input image?

Looking forward to receiving your reply soon. Thanks :-)

**Comment by lancercat** [comment]
(1) Convolution with 1*1 kernel, activated by sigmoid for heatmap and apply it back for a weighted sum.

For more details:
https://github.com/lancercat/VSDF/blob/8ffef1b65bd9147268a5f2f2cdaf5dac4af5433b/neko_2021_mjt/modulars/spatial_attention.py#L31

(2) It Resizes the image to 32 px by height keeping the aspect ratio, then center pads [1] it into 32*64 image.

For more details:
https://github.com/lancercat/VSDF/blob/8ffef1b65bd9147268a5f2f2cdaf5dac4af5433b/neko_2021_mjt/configs/data/hwdbch_data.py#L16

[1] Center padding gets inherited from https://github.com/Wang-Tianwei/Decoupled-attention-network

**Comment by bad-meets-joke** [comment]
Thank you.
